@startuml iniciarSesion

/'El caso de uso comienza cuando un usuario, que no tiene una sesión iniciada,
desea ingresar al sistema. Para ello, el sistema solicita su identificador y su
contraseña. El usuario ingresa ambos datos y, si la contraseña es correcta, el
sistema inicia la sesión. En caso contrario, el sistema informa que los datos
ingresados no son válidos y el usuario puede volver a intentar o cancelar el caso
de uso.'/
!theme vibrant
header PAV - Laboratorio 3

title DSS - Iniciar Sesión

group DSS - Iniciar Sesión
|||
actor Usuario
|||

loop mientras no cancela && !sesionIniciada

    Usuario -> .Sistema : sesionIniciada := iniciarSesion(id: string, password: string) : bool
    note right: El sistema recuerda la sesión del usuario si los datos son válidos
    |||

    opt cancela
        Usuario -> .Sistema : cancelarInicioSesion()
        note right: Cancela limpia la memoria
    end
    |||

end

|||
end
@enduml