@startuml
/' El caso de uso comienza cuando un funcionario, que previamente ha iniciado
sesión, desea eliminar un material. El sistema muestra la lista de materiales
registrados indicando su código y título, y el funcionario selecciona uno. Luego, el
sistema muestra la información del material seleccionado y solicita confirmación
de la operación. Si el funcionario confirma, el sistema elimina el material.'/


title Caso de uso 7

group DSS - Eliminar material
Actor Funcionario
|||
note left of Funcionario #aqua
<<Datatypes>>
DTMaterialResumen
-----------
codigo: string
titulo: string
end note

note left of Funcionario #aqua
<<Datatypes>>
DTMaterialDetalle
-----------
codigo: string
titulo: string
anioPublicacion: integer
tipoMaterial: string
puntajePromedio: float
end note


Funcionario -> .Sistema : listarMateriales() : Lista<DTMaterialResumen>
note right: El sistema muestra la lista de materiales, con código y titulo

Funcionario -> .Sistema : seleccionarMaterial(codigo: String) : DTMaterialDetalle
note right: El sistema muestra la información del material seleccionado y solicita confirmación

opt cancela
        Funcionario -> .Sistema : cancelarOperacion()
        note right: Cancela el borrado
    end

Funcionario -> .Sistema : confirmarEliminacion() : bool
note right : El sistema elimina el material

end
|||
|||
|||

@enduml