@startuml cerrarSesion
!theme vibrant
header PAV


title Caso de uso 2 - Cerrar Sesión

group DSS - Cerrar sesión

Actor Usuario

note left of Usuario #aqua
end note

note left of Usuario #aqua
end note


Usuario -> ":Sistema" : cerrarSesion()
note right: El sistema elimina la sesión activa en memoria



|||
|||
|||
end
|||
|||
|||
@enduml