@startuml registrarLector
!theme vibrant
header PAV


title Caso de uso 3 - Registrar Lector

group DSS - Registrar lector - con memoria
Actor Funcionario

note left of Funcionario #aqua
<<Datatypes>>
DTLector
-----------
ID: string
Nombre: string
password: string
Fecha: DTFecha

end note



loop no cancela && !confirma

Funcionario -> ":Sistema" : ingresarDatosLector (id:String,nombre:String,pass:String, DTFecha) : DTLector

note right: El sistema recuerda ID, Nombre, Password y Fecha

|||
|||
opt cancela
Funcionario -> ":Sistema" : cancelar()
note right: Cancela limpia la memoria
end

Funcionario -> ":Sistema" : confirma:= confirmarRegistro() :bool



end


note left of Funcionario #aqua
<<Datatypes>>
DTFecha
-----------
dia: integer
mes: string
año: integer

end note


end
|||
|||
|||
@enduml