@startuml registrarPrestamo
!theme vibrant
header PAV

title Caso de uso - 6 - Registrar Préstamo

group DSS - Registrar Préstamo
Actor Funcionario

note left of Funcionario #aqua
<<Datatypes>>
DTLector
-----------
ID: string
Nombre: string
password: string
Fecha: DTFecha
end note

note left of Funcionario #aqua
<<Datatypes>>
DTMaterial
-----------
codigo: string
titulo: string
autor: string
disponible: boolean
end note

note left of Funcionario #aqua
<<Datatypes>>
DTFecha
-----------
dia: integer
mes: string
año: integer
end note

loop mientras no cancela && !confirmado

    Funcionario -> .Sistema : ingresarIDLector(id:String) : DTLector
    note right: El sistema retorna los datos básicos del lector

    |||

    Funcionario -> .Sistema : ingresarCodigoMaterial(codigo:String) : DTMaterial
    note right: El sistema retorna la información del material

    |||

    Funcionario -> .Sistema : ingresarDatosPrestamo(fechaPrestamo:DTFecha, diasDevolucion:Integer) : DTDatosPrestamo
    note right: El sistema recuerda fecha y días de devolución\ny presenta los datos para confirmación

    |||

    opt cancela
        Funcionario -> .Sistema : cancelarRegistro()
        note right: Cancela limpia la memoria
    end

end

|||

Funcionario -> .Sistema : confirmarPrestamo() : bool
note right: El sistema registra el préstamo

|||
|||

end
@enduml