@startuml iniciarSesion
!theme vibrant
header PAV


title Caso de uso 1

group DSS - Escribir email

Actor Usuario

note left of Usuario #aqua
<<Datatypes>>
DTContacto
-----------
Nombre: string
email: string
end note

note left of Usuario #aqua
<<Datatypes>>
DTContactoTipo
-----------
email: string
tipo: TipoContacto
end note

note right of .Sistema #yellow
<<Ennumeration>>
TipoContacto
-----------
Principal
Con Copia
Con Copia Oculta
end note

Usuario -> .Sistema : escribirEmail (cuerpo:String,asunto:String) : Set (DTContacto)
note right: El sistema recuerda cuerpo y asunto 
|||
|||
Usuario -> .Sistema : elegirContactos (contactos:set(DTContactoConTipo))
note right: El sistema recuerda contactos elegidos 
|||
|||
opt si lo desea
Usuario -> .Sistema : agregarDestinatarios (destinatarios:set(DTContactoConTipo))
note right: El sistema recuerda destinatarios
end
|||
|||
Usuario -> .Sistema : enviarCorreo()
note right: El sistema libera la memoria

|||
|||
|||
end
|||
|||
|||
@enduml